package com.score.dao;

import com.score.bean.TScore;
import java.util.List;

public interface TScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int insert(TScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    TScore selectByPrimaryKey(Integer scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    List<TScore> selectAll(TScore score);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TScore record);
    //判断类型已经添加了几次
    int countByType(TScore record);
}